apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  # Replace ARGOCD_SERVER with your ArgoCD server name (see https://medium.com/dzerolabs/installing-ambassador-argocd-and-tekton-on-kubernetes-540aacc983b9)
  ARGOCD_SERVER: do-challenge.thelearning.dev
  ARGOCD_APPLICATION_NAME: flask-app
  ARGOCD_APPLICATION_REVISION: HEAD

